name: 'Local Action'
description: 'Runs a composite step action'
inputs:
  name:
    required: true
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Step operations
      id: step1
      run: |
        echo Hello ${{ inputs.name }}
        echo List directory files
        ls
        echo "::set-output name=random::$(echo $RANDOM)"
      shell: bash