name: 15 - Push Dev

on:
  push:
    branches:
    - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands
        run: |
          echo "Hello World"
          echo "This workflow only runs for push to the dev branch"