name: 18 - Specific File

on:
  push:
    paths:
      - '**/report.txt'
      - '**/README.md'
  pull_request:
    paths:
      - '**/report.txt'
      - '**/README.md'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Github context for the triggered event
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo "The ... file has been updated"