name: 2 - Secret Workflow

on:
  schedule:
  - cron: "0 4 * * *" # Runs at 04:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands with Secret
        env:
            SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
        run: |
          echo "Hello World"
          echo "This is a secret value: $SECRET_VALUE"
