name: 22 - Install Runner tools

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Install Commands
        run: |
          apt-cache update
          apt-cache install devscripts
          apt-cache install dput