name: 26 - Create release branch on another repo

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Generate release on documentation repo
        run: |
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/ZupIT/docs-ritchie.git
          cd docs-ritchie/
          ls -lha
          git init
          git checkout -b test-${{ steps.vars.outputs.tag }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . ; git commit -m "Creating new release according the Ritchie CLI tag ${{ steps.vars.outputs.tag }}"
          git push origin test-${{ steps.vars.outputs.tag }}
