name: 30 - Webhook Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag that will be created (ex: v1.2.4)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            
      - name: Echo
        run: echo "Tag Name" ${{ steps.get_version.outputs.VERSION }}
        
      - name: Trigger webhook
        run: |
          curl -X POST https://o2dla1l2qd.execute-api.us-east-1.amazonaws.com/prod/git \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          --data '{"zipURL": "https://github.com/GuillaumeFalourd/poc-github-actions/archive/refs/tags/${{ steps.tag.outputs.result }}.zip", "name": "workflow", "version": "${{ steps.tag.outputs.result }}"}'
