name: Workflow call

on:
  push:

jobs:
  call-workflow-passing-data:
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/33-reusable-workflow.yml@d11026c2ae2d5a56411b6b263514616d465ce406
    with:
      username: Guillaume
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
