name: Workflow call

on:
  push:

jobs:
  call-workflow-passing-data:
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/33-reusable-workflow.yml@cf4bb7af04777f4c6f41e9db36f393a4164125f6
    with:
      username: Guillaume
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
