name: 48 - Wait for Reusable Completion

on:
  workflow_call:

jobs:
  job-reusable-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Waiting 1 minute..."
        sleep 60
        echo "Hello World"