name: 49 - Rename on Release # https://stackoverflow.com/questions/71270252/rename-a-file-based-on-release

on:
  push:
    tags:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: env list
        run: env
      - run: echo $GITHUB_REF_NAME

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: echo $GITHUB_REF_NAME
      - run: install -Dv /dev/null ./Code/.pio/build/attiny841/firmware.hex
      - run: echo "test" >> ./Code/.pio/build/attiny841/firmware.hex
      - run: mv ./Code/.pio/build/attiny841/firmware.hex ./Code/.pio/build/attiny841/megadesk-$GITHUB_REF_NAME.hex
      - run: cat ./Code/.pio/build/attiny841/megadesk-$GITHUB_REF_NAME.hex
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./Code/.pio/build/attiny841/megadesk-$GITHUB_REF_NAME.hex 
