name: 5 - Container Workflow

on:
  schedule:
  - cron: "0 0 * * *" # Runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://guillaumefalourd/ritchiecli:go-1.15.8

    steps:
      - name: Run Commands using Golang
        run: |
              sudo rit -v
              sudo go version