name: 57 - Reusable outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/57-reusable-workflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}