name: 8 - Outputs Workflow

on:
  schedule:
    - cron: "0 6 * * *" # Runs at 6:00 UTC everyday
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"

  job2:
    runs-on: ubuntu-latest
    # Wait from the job1 to be completed before starting job2
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - run: echo "Goodbye"
