name: Python Script Container Workflow

on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://python:3.8-slim-buster
    steps:
      - name: Execute Python script # Run the run.py to get the latest data
        run: |
          python /github/workflow/run.py