name: Python Script Workflow

    on:
      schedule:
        - cron: "0 4 * * *" # Runs at 04:00 UTC everyday
      workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository content
            uses: actions/checkout@v2 # Checkout the repository content to github runner.

          - name: Setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 # Install the python version needed

          - name: Install dependencies
            run: python -m pip install --upgrade pip #dependency1 dependency2 ...

          - name: Execute py script # Run the run.py to get the latest data
            run: |
              python run.py