name: Python Script Container Workflow

on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://guillaumefalourd/ritchiecli:py-3.8
    steps:
      - name: Execute Python script # Run the run.py to get the latest data
        run: |
          echo "PATH -------------"
          ls -lha
          echo "PATH -------------"
          find ~/ -type f -name "run.py"
          python run.py