name: Python Script Container Workflow

on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://python:3.8-slim-buster
    steps:
      - name: Execute Python script # Run the run.py to get the latest data
        run: |
          echo "GITHUB -------------"
          ls -lha /github
          echo "GITHUB HOME -------------"
          ls -lha /github/home
          echo "GITHUB WORKFLOW -------------"
          ls -lha /github/workflow
          echo "DEV -------------"
          ls -lha /dev
          echo "SCRIPT -------------"
          python /github/workspace/run.py