name: Test 11

on: [push, pull_request]

jobs:
    job1:
        name: Check1
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'GuillaumeFalourd' }}
        steps:
          - run: echo "Actor isn't GuillaumeFalourd"

    job2:
        name: Check2
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'GuillaumeFalourd' }}
        steps:
          - run: echo "Actor is GuillaumeFalourd"