name: Test Windows commands

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: |
          md .os
          ls -lha
          curl -SLO https://v3.ritchiecli.io/3.1.0/windows/rit.exe
          ls -lha
          move .\\rit.exe .\\.os
          ls -lha
          set PATH=%PATH%;C:.\\.os
        shell: powershell