name: Test 11
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Test"
