name: Workflow Tester

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{github.ref}}

      - uses: jonabc/setup-licensed@v1
        with:
          version: 2.x
      - run: licensed list