name: Test 4

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands
        run: |
          echo "Hello World"
          echo "Test"
          echo "This workflow only runs for push to the DEV branch"
