name: Test 13

on:
  push:

jobs:
  call-workflow:
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/33-reusable-workflow.yml@main
    with:
      username: Guillaume
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
