name: Test 13

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string

jobs:
  call-workflow:
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/33-reusable-workflow.yml@${{ github.event.inputs.branch }}
    with:
      username: Guillaume
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
