name: Test 10

on:
  workflow_dispatch:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: |
          ls
          md .os
          ls
          Invoke-WebRequest -Uri "https://v3.ritchiecli.io/3.1.0/windows/rit.exe" -OutFile rit.exe
          ls
          move .\\rit.exe .\\.os
          ls
          set PATH=%PATH%;C:.\\.os
        shell: powershell