name: Test 11
on:
    pull_request:
        branches:
            - dev

defaults:
    run:
        shell: bash

jobs:
    somting:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Test"
