name: Test 16 #https://stackoverflow.com/questions/70290183/github-actions-pull-request-when-base-branch-has-name-something-not-target

on:
  pull_request_target:
    branches:
      - 'something\/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Something"