name: Test 5

env:
  REPORT_PATH: '**/report.txt'
  README_PATH: '**/README.md'

on:
  push:
    paths:
      - ${{ env.REPORT_PATH }}
      - ${{ env.README_PATH }}
  pull_request:
    paths:
      - ${{ env.REPORT_PATH }}
      - ${{ env.README_PATH }}
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $REPORT_PATH
          echo $README_PATH
      - run: |
          echo ${{ env.REPORT_PATH }}
          echo ${{ env.README_PATH }}