name: Test 18 #https://stackoverflow.com/questions/70326569/github-workflow-how-to-conditionally-setup-env-for-all-subsequent-jobs

on:
  workflow_dispatch:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test-env.outputs.test }}
    steps:
      - uses: actions/checkout@v2

      - name: Set exported variable
        id: test-env
        run: |
          if [ ${{ github.ref }} != 'refs/heads/main' ]; then
            echo "IS NOT main branch"
            echo "test=abc" >> $GITHUB_ENV
            echo "::set-output name=test::abc"
          else
            echo "IS main branch"
            echo "test=123" >> $GITHUB_ENV
            echo "::set-output name=test::123"
          fi
        shell: bash

      - name: Read exported variable
        run: |
          echo "$test"
          echo "ENV: ${{ env.test }}"
          echo "OUTPUT: ${{ steps.check.test-env.test }}"

  test2:
    runs-on: ubuntu-latest
    needs: [test1]
    steps:
      - uses: actions/checkout@v2
      - name: Read exported variable
        run: |
          echo "ENV ${{ env.test }}"
          echo "OUTPUT: ${{needs.test1.outputs.output1}}"
