name: Test 10

on:
  workflow_dispatch:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: |
          md .os
          ls
          echo "= = = DOWNLOAD = = = "
          Invoke-WebRequest -Uri "https://v3.ritchiecli.io/3.1.0/windows/rit.exe" -OutFile rit.exe
          ls
          echo "= = = MOVE = = = "
          move .\\rit.exe .\\.os
          ls
          echo "= = = OS = = = "
          cd .os
          ls
          echo "= = = PWD = = = "
          pwd
          echo "= = = PATH = = = "
          set CurrentDir="%~dp0"
          $PWD = Get-Location
          echo "PWD:" $PWD
          echo "= = = SET PATH = = = "
          $PATH = [Environment]::GetEnvironmentVariable("PATH")
          [Environment]::SetEnvironmentVariable("PATH", "$PATH;$PWD")
        shell: powershell
      - name: Teste 1
        if: always()
        run: |
          cd .os
          .\rit.exe --version
      - name: Teste 2
        if: always()
        run: rit --version