name: Test 63 # Related to https://stackoverflow.com/questions/74117204/how-to-generate-a-new-string-by-combine-github-action-workflow-variables

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check context var
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.sha }}
      
      - name: Setup env var
        run: |
          echo MESSAGE_SHA=(${{ github.event.head_commit.message }}-${{ github.sha }}) >> $GITHUB_ENV

      - name: Check env var
        run: |
          echo ${{ env.MESSAGE_SHA }}