name: Test 38 # Related to https://stackoverflow.com/questions/72558396/custom-default-value-for-github-actions

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Release Notes'
        required: false
        default: Build by ${{github.actor}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value
        run: echo "${{ inputs.test }}"


