name: Workflow Tester

on: [push, workflow_dispatch]

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: CD
        run: |
          cd /usr/local/bin
          ls -lha