name: Test 6

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        prev_price=9.88
        cur_price=10.2
        echo "this is the current price ${cur_price}"
        echo "this is the previous price ${prev_price}"
        price_limit=8.81
        echo "this is the price limit ${price_limit}"
        echo "GITHUB_PRICE_LIMIT=${price_limit}" >> $GITHUB_ENV
        echo "GITHUB_CUR_PRICE=${cur_price}" >> $GITHUB_ENV
        echo "GITHUB_PREV_PRICE=${prev_price}" >> $GITHUB_ENV
        echo "GITHUB_MAIL_UPDATE=0" >> $GITHUB_ENV
    - name: Print variables
      run: |
        echo ${{ env.GITHUB_CUR_PRICE }}
        echo ${{ env.GITHUB_PRICE_LIMIT }}
        echo ${{ env.GITHUB_PREV_PRICE }}
    - name: test for limit event 1
      if: ${{ (((env.GITHUB_CUR_PRICE >= env.GITHUB_PRICE_LIMIT) && (env.GITHUB_PREV_PRICE < env.GITHUB_PRICE_LIMIT)) || ((env.GITHUB_CUR_PRICE <= env.GITHUB_PRICE_LIMIT) &&  (env.GITHUB_PREV_PRICE > env.GITHUB_PRICE_LIMIT))) }}
      run: |-
        echo "limit event occurred 1"
    - name: test for limit event 2
      if: ${{ ((( ${{ env.GITHUB_CUR_PRICE }} >= ${{ env.GITHUB_PRICE_LIMIT }}) && (${{env.GITHUB_PREV_PRICE}} < ${{env.GITHUB_PRICE_LIMIT}})) || ((${{env.GITHUB_CUR_PRICE}} <= ${{env.GITHUB_PRICE_LIMIT}}) &&  (${{env.GITHUB_PREV_PRICE}} > ${{env.GITHUB_PRICE_LIMIT}}))) }}
      run: |-
        echo "limit event occurred 2"