name: Test 64 # Related to https://stackoverflow.com/questions/74125082/new-format-of-output-in-custom-github-actions-since-set-output-is-going-to-be-de

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Execute Python script # Run the run.py to get the latest data
        id: test1
        run: python new-output.py

      - run: |
          echo ${{steps.test1.outputs.test}}
          echo ${{env.TEST1}}

  job2:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
      - run: |
          echo ${{steps.step1.outputs.test}}
          echo ${{steps.step2.outputs.test}}