name: Test 36 # Related to https://stackoverflow.com/questions/72532083/how-to-access-this-json-object-field-in-github-actions

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Access GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Other variables
        run: |
          echo "Commits:" ${{ github.event.commits[0] }}
          echo "Message:" $MESSAGE
          echo "Author Email:" $(jq '.email' $AUTHOR)
          echo "Author Name:" $(jq '.name' $AUTHOR)
          echo "Author Username:" $(jq '.username' $AUTHOR)
          echo "Committer Email:" $(jq '.email' $COMMITTER)
          echo "Committer Name:" $(jq '.name' $COMMITTER)
          echo "Committer Username:" $(jq '.username' $COMMITTER)
        env:
          MESSAGE: ${{ toJSON(github.event.commits[0].message) }}
          AUTHOR: ${{ toJSON(github.event.commits[0].author) }}
          COMMITTER: ${{ toJSON(github.event.commits[0].committer) }}
