name: Workflow Tester

on: [workflow_dispatch]

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jonabc/setup-licensed@v1
        with:
          version: '2.1' # required: must satisfy semver.validRange
#          install-dir: /path/to/install/at # optional: defaults to /usr/local/bin
          github_token: {{ secrets.ACCESS_TOKEN }}
      - run: npm install
      - run: licensed list