name: Test 54 #Related to SO https://stackoverflow.com/questions/73611201/how-to-get-inputs-in-github-yml

on:
  push:
  workflow_dispatch:
    inputs:
       test1:
         description: test1
         required: false
         default: false
         type: boolean
       test2:
         description: test2 
         required: false
         default: true
         type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo ${{ inputs.test1 }}
            echo ${{ inputs.test2 }}

  job2:
    runs-on: ubuntu-latest
    if: ${{ inputs.test1 }}
    steps:
        - run: |
            echo ${{ inputs.test1 }}
            echo ${{ inputs.test2 }}

  job3:
    runs-on: ubuntu-latest
    if: ${{ inputs.test2 }}
    steps:
        - run: |
            echo ${{ inputs.test1 }}
            echo ${{ inputs.test2 }}