name: Test 36 # Related to https://stackoverflow.com/questions/72532083/how-to-access-this-json-object-field-in-github-actions

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Access GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Other variables with ENV
        run: |
          echo "Commits:" $COMMITS
          echo "Message:" $MESSAGE
          echo "Author Email:" $(echo $AUTHOR | jq -r '.email')
          echo "Author Name:" $(echo $AUTHOR | jq -r '.name')
          echo "Author Username:" $(echo $AUTHOR | jq -r '.username')
          echo "Committer Email:" $(echo $COMMITTER | jq -r '.email')
          echo "Committer Name:" $(echo $COMMITTER | jq -r '.name')
          echo "Committer Username:" $(echo $COMMITTER | jq -r '.username')
        env:
          COMMITS: ${{ toJSON(github.event.commits[0]) }}
          MESSAGE: ${{ toJSON(github.event.commits[0].message) }}
          AUTHOR: ${{ toJSON(github.event.commits[0].author) }}
          COMMITTER: ${{ toJSON(github.event.commits[0].committer) }}
