name: Test 36 # Related to https://stackoverflow.com/questions/72532083/how-to-access-this-json-object-field-in-github-actions

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Access GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo ${{ github.event.commits[0].message }}
          echo "$GITHUB_CONTEXT"
          echo "Event:" ${{ github.event }}
          echo "Commits:" ${{ github.event.push.commits[0] }}
          echo "Author:" ${{ github.event.push.commits.author }}
          echo "Committer:" ${{ github.event.push.commits.committer }}
