name: Test 10

on:
  workflow_dispatch:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create binary from branch
        run: |
          md .os
          ls
          echo "= = = DOWNLOAD = = = "
          Invoke-WebRequest -Uri "https://v3.ritchiecli.io/3.1.0/windows/rit.exe" -OutFile rit.exe
          ls
          echo "= = = MOVE = = = "
          move .\\rit.exe .\\.os
          ls
          echo "= = = OS = = = "
          cd .os
          ls
          echo "= = = PWD = = = "
          pwd
          echo "= = = PATH = = = "
          $PATH = [Environment]::GetEnvironmentVariable("PATH")
          $pwd = echo pwd
          [Environment]::SetEnvironmentVariable("PATH", "$PATH;$pwd")
        shell: powershell
      - name: Teste
        run: |
          .\rit.exe --version
          echo teste
          rit -v