name: Test 73 # Related to https://stackoverflow.com/questions/74644525/how-to-run-a-reusable-workflow-conditionnaly

on:
  workflow_dispatch:
    inputs:
      skip:
        type: boolean
        description: skip the workflow or not
        required: true
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.skip }}

  build:
    name: build
    if: ${{ inputs.skip == 'false' }}
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/workflow-tester52-reusable.yml@main
    with:
      input_var: 'something'
      another_input_var: 'something else'
    secrets: inherit